# Generated by Django 5.1.3 on 2024-11-22 07:57

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('service_client', 'Service Client'), ('gestionnaire', 'Gestionnaire des Demandes')], default='service_client', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('n_cin', models.CharField(max_length=12)),
                ('statut_familial', models.CharField(max_length=50)),
                ('nbr_dependant', models.IntegerField(blank=True, null=True)),
                ('situation_professionnelle', models.CharField(max_length=50)),
                ('titre_emploie', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_employeur', models.CharField(blank=True, max_length=255, null=True)),
                ('duree_emploie', models.IntegerField(blank=True, null=True)),
                ('revenu_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depense_mensuelles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dettes_existantes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('situation_bancaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_document', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_status', models.CharField(choices=[('Nouveau', 'Nouveau Client'), ('Ancien', 'Ancien Client')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SousTypeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('montant_min', models.DecimalField(decimal_places=2, default=300000, max_digits=12)),
                ('montant_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_min', models.IntegerField()),
                ('duree_max', models.IntegerField()),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prefixe', models.CharField(default='CPSA', max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_credit', models.CharField(max_length=20, unique=True)),
                ('duree', models.IntegerField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_payer_mois', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_credit', models.TextField()),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('statut_demande', models.CharField(choices=[('en_attente', 'En attente'), ('en_attente_signature', 'En attente de signature'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('date_derniere_maj', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.client')),
                ('sous_type_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.soustypecredit')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_calculé', models.FloatField()),
                ('ratio_endettement', models.FloatField()),
                ('date_decision', models.DateField(default=datetime.date.today)),
                ('statut_final', models.CharField(choices=[('approuve', 'Approuvé'), ('rejete', 'Rejeté')], max_length=50)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('montant_accorde', models.FloatField(blank=True, null=True)),
                ('analyste_decision', models.CharField(blank=True, max_length=255, null=True)),
                ('justification_analyste', models.TextField(blank=True, null=True)),
                ('demande_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.demandecredit')),
            ],
        ),
        migrations.AddField(
            model_name='soustypecredit',
            name='type_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.typecredit'),
        ),
        migrations.CreateModel(
            name='RemboursementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('somme_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_paiement', models.IntegerField()),
                ('type_paiement', models.CharField(choices=[('normal', 'Normal'), ('anticipe', 'Remboursement anticipé')], default='normal', max_length=20)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='cemapp.demandecredit')),
            ],
            options={
                'ordering': ['numero_paiement'],
                'unique_together': {('demande', 'numero_paiement')},
            },
        ),
    ]
