# Generated by Django 5.1.3 on 2024-12-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0002_agence_capitale_total_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='capitale_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
