# Generated by Django 5.1.3 on 2024-11-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0002_remove_gestionnairedemande_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
