# Generated by Django 5.1.3 on 2025-01-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0003_alter_agence_capitale_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvousfinalisation',
            name='modification_count',
        ),
        migrations.RemoveField(
            model_name='rendezvousfinalisation',
            name='token',
        ),
        migrations.RemoveField(
            model_name='rendezvousinspection',
            name='modification_count',
        ),
        migrations.RemoveField(
            model_name='rendezvousinspection',
            name='token',
        ),
    ]
