# Generated by Django 5.1.3 on 2025-05-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0003_alter_agence_capitale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='n_identification',
            field=models.CharField(default='CEM 001', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='isBlackList',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DemandeReportEcheance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande_report', models.CharField(max_length=20, unique=True)),
                ('raison_report', models.TextField()),
                ('date_report', models.DateField()),
                ('demande_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.demandecredit')),
            ],
        ),
    ]
