# Generated by Django 5.1.3 on 2024-11-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0003_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
