# Generated by Django 5.1.3 on 2025-01-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0004_remove_rendezvousfinalisation_modification_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='montant_emprunts_en_cours',
        ),
    ]
