# Generated by Django 5.1.3 on 2025-05-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0004_agence_n_identification_client_isblacklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='n_identification',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Messagerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_rendezvous', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.client')),
            ],
        ),
    ]
