# Generated by Django 5.1.3 on 2025-05-25 21:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0005_alter_agence_n_identification_messagerie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagerie',
            name='client',
        ),
        migrations.RemoveField(
            model_name='messagerie',
            name='date_debut_rendezvous',
        ),
        migrations.AddField(
            model_name='messagerie',
            name='contenu',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='messagerie',
            name='date_envoi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='messagerie',
            name='destinataire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagerie',
            name='expediteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagerie',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
