# Generated by Django 5.1.3 on 2024-11-10 16:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0007_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(max_length=10)),
                ('n_cin', models.CharField(max_length=12)),
                ('statut_familial', models.CharField(max_length=50)),
                ('nbr_dependant', models.IntegerField(blank=True, null=True)),
                ('situation_professionnelle', models.CharField(max_length=50)),
                ('titre_emploie', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_employeur', models.CharField(blank=True, max_length=255, null=True)),
                ('duree_emploie', models.IntegerField(blank=True, null=True)),
                ('revenu_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depense_mensuelles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dettes_existantes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('situation_bancaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('duree_min', models.IntegerField()),
                ('duree_max', models.IntegerField()),
                ('montant_max', models.IntegerField()),
                ('taux_mensuel', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_credit', models.CharField(max_length=10, unique=True)),
                ('duree', models.IntegerField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_payer_mois', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_credit', models.TextField()),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('statut_demande', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.client')),
                ('type_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.typecredit')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_calculé', models.FloatField()),
                ('ratio_endettement', models.FloatField()),
                ('date_decision', models.DateField(default=datetime.date.today)),
                ('statut_final', models.CharField(choices=[('approuve', 'Approuvé'), ('rejete', 'Rejeté')], max_length=50)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('montant_accorde', models.FloatField(blank=True, null=True)),
                ('analyste_decision', models.CharField(blank=True, max_length=255, null=True)),
                ('justification_analyste', models.TextField(blank=True, null=True)),
                ('demande_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.demandecredit')),
            ],
        ),
        migrations.CreateModel(
            name='RemboursementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payement', models.DateTimeField()),
                ('somme_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('n_payement', models.IntegerField()),
                ('demande_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.demandecredit')),
            ],
        ),
    ]
