# Generated by Django 5.1.3 on 2024-11-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0008_client_typecredit_demandecredit_evaluationcredit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='matricule',
        ),
    ]
