# Generated by Django 5.1.3 on 2024-11-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0010_documentcredit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecredit',
            name='duree_max',
        ),
        migrations.RemoveField(
            model_name='typecredit',
            name='duree_min',
        ),
        migrations.RemoveField(
            model_name='typecredit',
            name='montant_max',
        ),
        migrations.RemoveField(
            model_name='typecredit',
            name='taux_mensuel',
        ),
    ]
