# Generated by Django 5.1.3 on 2024-11-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0011_remove_typecredit_duree_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousTypeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('montant_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_min', models.IntegerField()),
                ('duree_max', models.IntegerField()),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemapp.typecredit')),
            ],
        ),
    ]
