# Generated by Django 5.1.3 on 2024-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0012_soustypecredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustypecredit',
            name='montant_min',
            field=models.DecimalField(decimal_places=2, default=300000, max_digits=10),
        ),
    ]
