# Generated by Django 5.1.3 on 2024-11-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemapp', '0013_soustypecredit_montant_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soustypecredit',
            name='montant_max',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='soustypecredit',
            name='montant_min',
            field=models.DecimalField(decimal_places=2, default=300000, max_digits=12),
        ),
    ]
